name: Experiment
on: 
  schedule:
  - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      with: { ref: main }
    - name: List files
      run: ls
